import { useRef, useEffect, useState } from 'react'
import React from 'react'

/**
 * HealthCard — renders a shareable weekly summary card onto a <canvas>
 * and provides a download button.
 *
 * Props:
 *   username      {string}
 *   stats         { reminders, prescriptions, nutrition, yoga_streak }
 *   calorieGoal   {number}
 *   totalCalories {number}  — calories logged today
 */
export default function HealthCard({ username, stats, calorieGoal, totalCalories, onClose }) {
  const canvasRef = useRef(null)
  const [dataUrl, setDataUrl] = useState(null)

  useEffect(() => {
    const canvas  = canvasRef.current
    if (!canvas) return
    const ctx     = canvas.getContext('2d')
    const W = 700, H = 380
    canvas.width  = W
    canvas.height = H

    // ── background ────────────────────────────────────────────────
    const bg = ctx.createLinearGradient(0, 0, W, H)
    bg.addColorStop(0, '#0f172a')
    bg.addColorStop(1, '#1e293b')
    ctx.fillStyle = bg
    ctx.beginPath()
    roundRect(ctx, 0, 0, W, H, 24)
    ctx.fill()

    // ── accent bar left ───────────────────────────────────────────
    const accent = ctx.createLinearGradient(0, 0, 0, H)
    accent.addColorStop(0, '#e11d48')
    accent.addColorStop(1, '#f97316')
    ctx.fillStyle = accent
    ctx.beginPath()
    roundRect(ctx, 0, 0, 6, H, [6, 0, 0, 6])
    ctx.fill()

    // ── logo + title ──────────────────────────────────────────────
    ctx.fillStyle = '#e11d48'
    ctx.font      = 'bold 18px system-ui, sans-serif'
    ctx.fillText('♥ NutriCare-360', 32, 44)

    ctx.fillStyle = '#94a3b8'
    ctx.font      = '13px system-ui, sans-serif'
    ctx.fillText('Weekly Health Summary', 32, 66)

    // ── username ──────────────────────────────────────────────────
    ctx.fillStyle = '#f8fafc'
    ctx.font      = 'bold 28px system-ui, sans-serif'
    ctx.fillText(`@${username}`, 32, 108)

    // ── date ──────────────────────────────────────────────────────
    ctx.fillStyle = '#64748b'
    ctx.font      = '12px system-ui, sans-serif'
    const now = new Date()
    ctx.fillText(now.toLocaleDateString('en-US', { weekday:'long', month:'long', day:'numeric', year:'numeric' }), 32, 128)

    // ── divider ───────────────────────────────────────────────────
    ctx.strokeStyle = '#334155'
    ctx.lineWidth   = 1
    ctx.beginPath()
    ctx.moveTo(32, 148)
    ctx.lineTo(W - 32, 148)
    ctx.stroke()

    // ── stat boxes ───────────────────────────────────────────────
    const boxes = [
      { label: 'Reminders',     value: stats.reminders,    color: '#e11d48', icon: '🔔' },
      { label: 'Prescriptions', value: stats.prescriptions, color: '#0ea5e9', icon: '📄' },
      { label: 'Meals Logged',  value: stats.nutrition,    color: '#f59e0b', icon: '🍽' },
      { label: 'Active Days',   value: `${stats.yoga_streak ?? 0}/7`, color: '#8b5cf6', icon: '🔥' },
    ]
    const boxW = (W - 64 - 24) / 4
    boxes.forEach((box, i) => {
      const x = 32 + i * (boxW + 8)
      const y = 170

      // box background
      ctx.fillStyle = 'rgba(255,255,255,0.05)'
      roundRect(ctx, x, y, boxW, 100, 12)
      ctx.fill()

      // icon
      ctx.font      = '22px system-ui'
      ctx.fillText(box.icon, x + 14, y + 32)

      // value
      ctx.fillStyle = box.color
      ctx.font      = 'bold 26px system-ui, sans-serif'
      ctx.fillText(String(box.value), x + 14, y + 64)

      // label
      ctx.fillStyle = '#94a3b8'
      ctx.font      = '11px system-ui, sans-serif'
      ctx.fillText(box.label, x + 14, y + 82)
    })

    // ── calorie progress bar ──────────────────────────────────────
    const barY = 296
    ctx.fillStyle = '#1e293b'
    roundRect(ctx, 32, barY, W - 64, 18, 9)
    ctx.fill()

    const pct  = Math.min(1, totalCalories / calorieGoal)
    const barColor = pct >= 1 ? '#ef4444' : pct >= 0.8 ? '#f59e0b' : '#22c55e'
    ctx.fillStyle = barColor
    roundRect(ctx, 32, barY, Math.max(18, (W - 64) * pct), 18, 9)
    ctx.fill()

    ctx.fillStyle = '#94a3b8'
    ctx.font      = '12px system-ui, sans-serif'
    ctx.fillText(`Calories today: ${Math.round(totalCalories)} / ${calorieGoal} kcal`, 32, barY - 8)

    // ── footer ────────────────────────────────────────────────────
    ctx.fillStyle = '#475569'
    ctx.font      = '11px system-ui, sans-serif'
    ctx.fillText('Generated by NutriCare-360 • nutricare360.app', 32, H - 20)

    setDataUrl(canvas.toDataURL('image/png'))
  }, [username, stats, calorieGoal, totalCalories])

  const handleDownload = () => {
    const a = document.createElement('a')
    a.href     = dataUrl
    a.download = `nutricare360-${username}-${new Date().toISOString().slice(0,10)}.png`
    a.click()
  }

  return (
    <div className="modal-backdrop">
      <div className="modal-content animate-fade-up" style={{ maxWidth: '760px', width: '95vw' }}>
        <div className="modal-header">
          <h2><i className="fa-solid fa-share-nodes"></i> Share Health Card</h2>
          <button className="icon-btn" onClick={onClose}><i className="fa-solid fa-xmark"></i></button>
        </div>
        <div className="modal-body" style={{ padding: '1.5rem' }}>
          <canvas ref={canvasRef} style={{ width: '100%', borderRadius: '12px', display: 'block' }} />
          <div style={{ display: 'flex', gap: '1rem', marginTop: '1.25rem', justifyContent: 'flex-end' }}>
            <button className="btn btn-outline" onClick={onClose}>Close</button>
            <button className="btn btn-primary" onClick={handleDownload} disabled={!dataUrl}>
              <i className="fa-solid fa-download"></i> Download PNG
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// helper — rounded rect path
function roundRect(ctx, x, y, w, h, r) {
  if (typeof r === 'number') r = [r, r, r, r]
  const [tl, tr, br, bl] = r
  ctx.beginPath()
  ctx.moveTo(x + tl, y)
  ctx.lineTo(x + w - tr, y)
  ctx.quadraticCurveTo(x + w, y, x + w, y + tr)
  ctx.lineTo(x + w, y + h - br)
  ctx.quadraticCurveTo(x + w, y + h, x + w - br, y + h)
  ctx.lineTo(x + bl, y + h)
  ctx.quadraticCurveTo(x, y + h, x, y + h - bl)
  ctx.lineTo(x, y + tl)
  ctx.quadraticCurveTo(x, y, x + tl, y)
  ctx.closePath()
}
